CREATE TABLE IF NOT EXISTS employees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    "position" VARCHAR(50),
    salary BYTEA,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
