CREATE USER fdw_reader_db1 WITH PASSWORD 'fdw_reader_db1';

GRANT CONNECT ON DATABASE db1 TO fdw_reader_db1;

GRANT USAGE ON SCHEMA public TO fdw_reader_db1;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO fdw_reader_db1;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO fdw_reader_db1;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO fdw_reader_db1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO fdw_reader_db1;
